---
title: "Human data process"
author: "Sebastián Sáenz"
date: "09/11/2020"
output: github_document

---

```{r libraries, message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
```
## Dependencies
* `r R.version.string`
* `tidyverse` (v . `r packageVersion("tidyverse")`)


```{r summary_df}
summary_df <- read.table("data_raw/human/summary.txt",
                 header = TRUE,
                 sep = "\t",
                 check.names = FALSE)
```


```{r peptides_plot,}
summary_df %>%
  filter(!`Peptide Sequences Identified` > 30000) %>%
ggplot(aes(x =`Peptide Sequences Identified`)) +
  geom_histogram(binwidth = 100) +
  scale_x_continuous(breaks = seq(0, 10000, by = 500)) +
  ylab("Number of samples") +
  theme(axis.text.x = element_text(angle = 45))
```


```{r msms_plot}
ggplot(data = summary_df, aes(x =`MS/MS Identified [%]` )) +
  geom_histogram(binwidth = 1) +
  scale_x_continuous(breaks = seq(0,23, by = 1)) +
  scale_y_continuous(breaks = seq(0,70, by = 5)) +
  theme_classic()
```



```{r}
pep_mean <- mean(summary_df$`Peptide Sequences Identified`) 
```


## My computer

```{r sessioninfo, message=FALSE}
sessionInfo()
```

